using Imposter.Abstractions;
using MediatR;
using Microsoft.AspNetCore.Hosting;
using TransactionProcessor.BusinessLogic.Services;
using TransactionProcessor.BusinessLogic.Manager;
using Shared.EventStore.Aggregate;
using Shared.EntityFramework;
using Shared.EventStore.EventStore;
using SecurityService.Client;
using PataPawaPostPay;
using TransactionProcessor.BusinessLogic.OperatorInterfaces.PataPawaPostPay;
using MessagingService.Client;
using TransactionProcessor.Database.Contexts;
using TransactionProcessor.Repository;
using System.IO.Abstractions;
using TransactionProcessor.ProjectionEngine.Repository;
using TransactionProcessor.Models.Merchant;
using TransactionProcessor.BusinessLogic.OperatorInterfaces;
using TransactionProcessor.BusinessLogic.Common;

[assembly: GenerateImposter(typeof(IOperatorProxy))]
[assembly: GenerateImposter(typeof(ITransactionDomainService))]
[assembly: GenerateImposter(typeof(IMediator))]
[assembly: GenerateImposter(typeof(IWebHostEnvironment))]
[assembly: GenerateImposter(typeof(IVoucherDomainService))]
[assembly: GenerateImposter(typeof(IVoucherManagementManager))]
[assembly: GenerateImposter(typeof(ISettlementDomainService))]
[assembly: GenerateImposter(typeof(IFloatDomainService))]
[assembly: GenerateImposter(typeof(IAggregateService))]
[assembly: GenerateImposter(typeof(ITransactionProcessorManager))]
[assembly: GenerateImposter(typeof(ITransactionProcessorReadModelRepository))]
[assembly: GenerateImposter(typeof(IDbContextResolver<EstateManagementContext>))]
[assembly: GenerateImposter(typeof(IEventStoreContext))]
[assembly: GenerateImposter(typeof(ISecurityServiceClient))]
[assembly: GenerateImposter(typeof(ITransactionValidationService))]
[assembly: GenerateImposter(typeof(IMemoryCacheWrapper))]
[assembly: GenerateImposter(typeof(IFeeCalculationManager))]
[assembly: GenerateImposter(typeof(ITransactionReceiptBuilder))]
[assembly: GenerateImposter(typeof(IMessagingServiceClient))]
[assembly: GenerateImposter(typeof(PataPawaPostPayServiceClient))]
[assembly: GenerateImposter(typeof(IPataPawaPostPayService))]
[assembly: GenerateImposter(typeof(IStatementBuilder))]
[assembly: GenerateImposter(typeof(IFileSystem))]
[assembly: GenerateImposter(typeof(IDirectoryInfo))]
[assembly: GenerateImposter(typeof(ITransactionProcessorReadRepository))]
[assembly: GenerateImposter(typeof(IMerchantDomainService))]
