using Microsoft.IdentityModel.Logging;
using Microsoft.IdentityModel.Tokens;

namespace TransactionProcessor.Bootstrapper
{
    using System;
    using System.Diagnostics.CodeAnalysis;
    using System.IO;
    using System.Net.Http;
    using System.Reflection;
    using Common;
    using EventStore.Client;
    using Lamar;
    using Microsoft.AspNetCore.Authentication.JwtBearer;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Diagnostics.HealthChecks;
    using Microsoft.OpenApi.Models;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Serialization;
    using Shared.EventStore.Extensions;
    using Shared.Extensions;
    using Shared.General;
    using Swashbuckle.AspNetCore.Filters;

    /// <summary>
    /// 
    /// </summary>
    /// <seealso cref="Lamar.ServiceRegistry" />
    [ExcludeFromCodeCoverage]
    public class MiddlewareRegistry : ServiceRegistry
    {
        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="MiddlewareRegistry"/> class.
        /// </summary>
        public MiddlewareRegistry()
        {
            String connectionString = Startup.Configuration.GetValue<String>("EventStoreSettings:ConnectionString");
            EventStoreClientSettings eventStoreClientSettings = EventStoreClientSettings.Create(connectionString);

            this.AddHealthChecks()
                .AddEventStore(eventStoreClientSettings,
                               userCredentials: eventStoreClientSettings.DefaultCredentials,
                               name:"Eventstore",
                               failureStatus:HealthStatus.Unhealthy,
                               tags:new[] {"db", "eventstore"}).AddSecurityService(this.ApiEndpointHttpHandler);

            this.AddSwaggerGen(c =>
                               { 
                                   c.CustomSchemaIds(type => type.FullName); // Uses the full namespace as schema ID
                                   c.SwaggerDoc("v1",
                                                new OpenApiInfo
                                                {
                                                    Title = "Transaction Processor API",
                                                    Version = "1.0",
                                                    Description = "A REST Api to manage the processing and routing of transactions to local and remote operators.",
                                                    Contact = new OpenApiContact
                                                              {
                                                                  Name = "Stuart Ferguson",
                                                                  Email = "golfhandicapping@btinternet.com"
                                                              }
                                                });
                                   // add a custom operation filter which sets default values
                                   c.OperationFilter<SwaggerDefaultValues>();
                                   c.ExampleFilters();

                                   //Locate the XML files being generated by ASP.NET...
                                   var directory = new DirectoryInfo(AppContext.BaseDirectory);
                                   var xmlFiles = directory.GetFiles("*.xml");

                                   //... and tell Swagger to use those XML comments.
                                   foreach (FileInfo fileInfo in xmlFiles)
                                   {
                                       c.IncludeXmlComments(fileInfo.FullName);
                                   }
                               });

            this.AddSwaggerExamplesFromAssemblyOf<SwaggerJsonConverter>();

            IdentityModelEventSource.ShowPII = true;

            this.AddAuthentication(options =>
                                   {
                                       options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                                       options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                                       options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                                   }).AddJwtBearer(options =>
                                                   {
                                                       options.BackchannelHttpHandler = new HttpClientHandler
                                                                                        {
                                                                                            ServerCertificateCustomValidationCallback = (message,
                                                                                                certificate,
                                                                                                chain,
                                                                                                sslPolicyErrors) => true
                                                                                        };
                                                       options.Authority = GetSecurityServiceConfigValue("Authority");
                                                       options.Audience = GetSecurityServiceConfigValue("ApiName");

                                                       options.TokenValidationParameters = new TokenValidationParameters
                                                       {
                                                           ValidateAudience = false,
                                                           ValidAudience =
                                                               GetSecurityServiceConfigValue("ApiName"),
                                                           ValidIssuer =
                                                               GetSecurityServiceConfigValue("Authority"),
                                                       };
                                                       options.IncludeErrorDetails = true;
                                                   });

            this.AddControllers().AddNewtonsoftJson(options =>
                                                    {
                                                        options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
                                                        options.SerializerSettings.TypeNameHandling = TypeNameHandling.Auto;
                                                        options.SerializerSettings.Formatting = Formatting.Indented;
                                                        options.SerializerSettings.DateTimeZoneHandling = DateTimeZoneHandling.Utc;
                                                        options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                                                    });

            Assembly assembly = this.GetType().GetTypeInfo().Assembly;
            this.AddMvcCore().AddApplicationPart(assembly).AddControllersAsServices();

            this.ConfigureHttpJsonOptions(options =>
            {
                options.SerializerOptions.PropertyNamingPolicy = new SnakeCaseNamingPolicy();
                options.SerializerOptions.PropertyNameCaseInsensitive = true; // optional, but safer
            });
        }

        #endregion

        private String GetSecurityServiceConfigValue(String keyName) {
            return ConfigurationReader.GetValue("SecurityConfiguration", keyName);
        }

        #region Methods

        /// <summary>
        /// APIs the endpoint HTTP handler.
        /// </summary>
        /// <param name="serviceProvider">The service provider.</param>
        /// <returns></returns>
        private HttpClientHandler ApiEndpointHttpHandler(IServiceProvider serviceProvider)
        {
            return new HttpClientHandler
                   {
                       ServerCertificateCustomValidationCallback = (message,
                                                                    cert,
                                                                    chain,
                                                                    errors) =>
                                                                   {
                                                                       return true;
                                                                   }
                   };
        }

        #endregion
    }
}