name: Release

on:
  release:
    types: [published]

jobs:
  buildlinux:
    name: "Release"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
    - name: Restore Nuget Packages
      run: dotnet restore TransactionProcessor.sln --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }}

    - name: Build Code
      run: dotnet build TransactionProcessor.sln --configuration Release

    - name: Run Unit Tests
      run: |
        echo "ASPNETCORE_ENVIRONMENT are > ${ASPNETCORE_ENVIRONMENT}"
        dotnet test "TransactionProcessor.BusinessLogic.Tests\TransactionProcessor.BusinessLogic.Tests.csproj"
        dotnet test "TransactionProcessor.ProjectionEngine.Tests\TransactionProcessor.ProjectionEngine.Tests.csproj"
        dotnet test "TransactionProcessor.Aggregates.Tests\TransactionProcessor.Aggregates.Tests.csproj"
        dotnet test "TransactionProcessor.Tests\TransactionProcessor.Tests.csproj"        
        
    - name: Publish Images to Docker Hub - Pre Release
      if: ${{ github.event.release.prerelease == true }} 
      run: |
        docker build . --file TransactionProcessor/Dockerfile --tag stuartferguson/transactionprocessor:dev
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        docker push stuartferguson/transactionprocessor:dev

    - name: Publish Images to Docker Hub - Formal Release
      if: ${{ github.event.release.prerelease == false }} 
      run: |
        docker build . --file TransactionProcessor/Dockerfile --tag stuartferguson/transactionprocessor:latest
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        docker push stuartferguson/transactionprocessor:latest

    - name: Publish API
      if: ${{ github.event.release.prerelease == false }}
      run: dotnet publish "TransactionProcessor\TransactionProcessor.csproj" --configuration Release --output publishOutput -r win-x64 --self-contained

    - name: Build Release Package
      run: |
         cd /home/runner/work/TransactionProcessor/TransactionProcessor/publishOutput
         zip -r ../transactionprocessor.zip ./*

    - name: Upload the artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: transactionprocessor
        path: transactionprocessor.zip

    - name: Build and Publish Nuget Packages
      if: ${{ github.event.release.prerelease == false }}
      run: |
        dotnet pack "TransactionProcessor.Client\TransactionProcessor.Client.csproj" /p:PackageVersion=${{ steps.get_version.outputs.VERSION }} --output Nugets
        dotnet nuget push Nugets/TransactionProcessor.Client.${{ steps.get_version.outputs.VERSION }}.nupkg --api-key ${{ secrets.PRIVATEFEED_APIKEY }} --source ${{ secrets.PRIVATEFEED_URL }} --skip-duplicate
        dotnet pack "TransactionProcessor.DomainEvents\TransactionProcessor.DomainEvents.csproj" /p:PackageVersion=${{ steps.get_version.outputs.VERSION }} --output Nugets
        dotnet nuget push Nugets/TransactionProcessor.DomainEvents.${{ steps.get_version.outputs.VERSION }}.nupkg --api-key ${{ secrets.PRIVATEFEED_APIKEY }} --source ${{ secrets.PRIVATEFEED_URL }} --skip-duplicate
        dotnet pack "TransactionProcessor.IntegrationTesting.Helpers\TransactionProcessor.IntegrationTesting.Helpers.csproj" /p:PackageVersion=${{ steps.get_version.outputs.VERSION }} --output Nugets
        dotnet nuget push Nugets/TransactionProcessor.IntegrationTesting.Helpers.${{ steps.get_version.outputs.VERSION }}.nupkg --api-key ${{ secrets.PRIVATEFEED_APIKEY }} --source ${{ secrets.PRIVATEFEED_URL }} --skip-duplicate
        dotnet pack "TransactionProcessor.Database\TransactionProcessor.Database.csproj" /p:PackageVersion=${{ steps.get_version.outputs.VERSION }} --output Nugets -c Release
        dotnet nuget push Nugets/TransactionProcessor.Database.${{ steps.get_version.outputs.VERSION }}.nupkg --api-key ${{ secrets.PRIVATEFEED_APIKEY }} --source ${{ secrets.PRIVATEFEED_URL }} --skip-duplicate

  deploystaging:
    runs-on: stagingserver
    needs: buildlinux
    environment: staging
    name: "Deploy to Staging"
    
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: transactionprocessor

      - name: Remove existing  Windows service
        run: |
          $serviceName = "Transaction Processing - Transaction Processor"
          # Check if the service exists
          if (Get-Service -Name $serviceName -ErrorAction SilentlyContinue) {
            Stop-Service -Name $serviceName
            sc.exe delete $serviceName
          }

      - name: Unzip the files
        run: |
          Expand-Archive -Path transactionprocessor.zip -DestinationPath "C:\txnproc\transactionprocessing\transactionprocessor" -Force
      
      - name: Install as a Windows service
        run: |
          $serviceName = "Transaction Processing - Transaction Processor"
          $servicePath = "C:\txnproc\transactionprocessing\transactionprocessor\TransactionProcessor.exe"
                   
          New-Service -Name $serviceName -BinaryPathName $servicePath -Description "Transaction Processing - Transaction Processor" -DisplayName "Transaction Processing - Transaction Processor" -StartupType Automatic
          Start-Service -Name $serviceName

  deployproduction:
    runs-on: productionserver
    needs: [buildlinux, deploystaging]
    environment: production
    name: "Deploy to Production"
    
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: transactionprocessor

      - name: Remove existing  Windows service
        run: |
          $serviceName = "Transaction Processing - Transaction Processor"
          # Check if the service exists
          if (Get-Service -Name $serviceName -ErrorAction SilentlyContinue) {
            Stop-Service -Name $serviceName
            sc.exe delete $serviceName
          }

      - name: Unzip the files
        run: |
          Expand-Archive -Path transactionprocessor.zip -DestinationPath "C:\txnproc\transactionprocessing\transactionprocessor" -Force
      
      - name: Install as a Windows service
        run: |
          $serviceName = "Transaction Processing - Transaction Processor"
          $servicePath = "C:\txnproc\transactionprocessing\transactionprocessor\TransactionProcessor.exe"
                   
          New-Service -Name $serviceName -BinaryPathName $servicePath -Description "Transaction Processing - Transaction Processor" -DisplayName "Transaction Processing - Transaction Processor" -StartupType Automatic
          Start-Service -Name $serviceName
